<?php
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Master Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/master-subscription-agreement
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2012 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/

$dictionary['THHL_Parties'] = array(
	'table' => 'thhl_parties',
	'audited' => true,
	'duplicate_merge' => true,
	'indices' => array(
		array(
			'name' => 'party_id_number',
			'type' => 'unique',
			'fields' => array('party_id_number')
		),
	),
	'fields' => array(
		'fb_link' =>
		array(
			'required' => false,
			'name' => 'fb_link',
			'vname' => 'LBL_FB_LINK',
			'type' => 'url',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => '255',
			'size' => '20',
			'dbType' => 'varchar',
			'gen' => '0',
			'link_target' => '_blank',
		),
		'party_id_number' =>
		array(
			'dependency' => '',
			'required' => true,
			'name' => 'party_id_number',
			'vname' => 'LBL_PARTY_ID_NUMBER',
			'type' => 'int',
			'readonly' => true,
			'massupdate' => '0',
			'comments' => '',
			'help' => '',
			'importable' => 'false',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => '11',
			'auto_increment' => true,
			'disable_num_format' => '1',
		),
		'party_type' =>
		array(
			'required' => false,
			'name' => 'party_type',
			'vname' => 'LBL_PARTY_TYPE',
			'type' => 'enum',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'options' => 'party_type_list',
			'default' => '',
			'calculated' => false,
		),
		'party_password' =>
		array(
			'required' => false,
			'name' => 'party_password',
			'vname' => 'LBL_PARTY_PASSWORD',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'dependency' => 'equal($party_type,"Private")',
			'len' => 100,
			'size' => '20',
		),
		'start_time' =>
		array(
			'required' => false,
			'name' => 'start_time',
			'vname' => 'LBL_START_TIME',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
		),
		'end_time' =>
		array(
			'required' => false,
			'name' => 'end_time',
			'vname' => 'LBL_END_TIME',
			'type' => 'datetimecombo',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'size' => '20',
			'enable_range_search' => false,
			'dbType' => 'datetime',
		),
		'party_host' =>
		array(
			'required' => true,
			'source' => 'non-db',
			'name' => 'party_host',
			'vname' => 'LBL_PARTY_HOST',
			'type' => 'relate',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => '255',
			'size' => '20',
			'id_name' => 'host_id',
			'ext2' => 'THHL_PartyAnimals',
			'module' => 'THHL_PartyAnimals',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),
		'host_id' =>
		array(
			'name' => 'host_id',
			'vname' => 'LBL_HOST_ID',
			'type' => 'id',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'module' => 'THHL_PartyAnimals',
			'studio' => 'hidden',
		),
		'party_address_city' =>
		array(
			'required' => false,
			'name' => 'party_address_city',
			'vname' => 'LBL_PARTY_ADDRESS_CITY',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => 100,
			'size' => '20',
			'group'=>'party_address',
		),
		'party_address_state' =>
		array(
			'required' => false,
			'name' => 'party_address_state',
			'vname' => 'LBL_PARTY_ADDRESS_STATE',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => 100,
			'size' => '20',
			'group'=>'party_address',
		),
		'party_address_postalcode' =>
		array(
			'required' => false,
			'name' => 'party_address_postalcode',
			'vname' => 'LBL_PARTY_ADDRESS_POSTALCODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => 20,
			'size' => '20',
			'group'=>'party_address',
		),
		'party_address_country' =>
		array(
			'required' => false,
			'name' => 'party_address_country',
			'vname' => 'LBL_PARTY_ADDRESS_COUNTRY',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => 100,
			'size' => '20',
			'group'=>'party_address',
		),
		'party_address_street' =>
		array(
			'required' => false,
			'name' => 'party_address_street',
			'vname' => 'LBL_PARTY_ADDRESS',
			'type' => 'varchar',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'calculated' => false,
			'len' => '255',
			'size' => '20',
			'group'=>'party_address',
		),
	),
	'relationships' => array(
	),
	'optimistic_locking' => true,
	'unified_search' => true,
);
if(!class_exists('VardefManager')){
	require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('THHL_Parties', 'THHL_Parties', array('basic', 'assignable'));